#+OPTIONS: author:nil ^:{}
#+HUGO_FRONT_MATTER_FORMAT: YAML
#+HUGO_BASE_DIR: ~/blog/
#+HUGO_SECTION: posts
#+DATE:<2024-01-21 Sun>
#+HUGO_CUSTOM_FRONT_MATTER: :toc true
#+HUGO_AUTO_SET_LASTMOD: t
#+HUGO_TAGS: "Abstract Algebra"
#+HUGO_DRAFT: false
#+LATEX_HEADER: \usepackage{amsmath}
#+LATEX_HEADER: \usepackage{amssymb}
#+TITLE: 群在集合上的作用
* 例题
1. 设群 $G$ 作用在集合 \Sigma 上. 令 $t$ 表示 \Sigma 在 $G$ 作用下的轨道个数,
   对任意 $g \in G$, $f(g)$ 表示 \varepsilon 在 $g$ 作用下的不动点个数. 试证
   $$\sum_{g \in G}{f(g)} = t|G|.$$
   这就是说, $G$ 的每个元素在 \Sigma 上作用平均使得 $t$ 个文字不动.

   证明:

   $$\sum_{g \in G}f(g) = \sum_{a \in \Sigma}|G_{a}| = \sum_{a \in \Sigma}\frac{|G|}{|[a]|} = \sum_{i = 1}^t\sum_{j = 1}^{|[a_i]|}\frac{|G|}{|[a_i]|} = t|G|.$$

   证毕.

2. 设 $p$ 是一个素数, $G$ 是 $p$ 的方幂阶的群. 试证 $G$ 的非正规子群的个数一定是 $p$ 的倍数.

   证明:

   若 $A$ 是 $G$ 的非正规子群, 考虑从 $G$ 对 $A$ 的共轭表示 $\pi$,
   $\Sigma = \{aAa^{-1} | a \in G\}$, $\pi(g) = gaAa^{-1}g^{-1}$,
   $[A]$ 即为 $A$ 的所有共轭子群, 根据轨道公式, $|[A]|$ 整除 $|G|$,
   故 $[A]$ 的大小是 $p$ 的倍数, 从而 G 的非正规子群的个数一定是 $p$ 的倍数.

3. 令 $G$ 是一个单群, 如果存在 $G$ 的真子群 $H$ 使得 $[G:H] \leqslant 4$, 则 $|G| \leqslant 3$.

   证明:

   考虑 $G$ 对 $H$ 的左诱导表示, 则存在 $G$ 到 $S_m$ 的同态 $\rho$, $m \leqslant 4$.
   由于 $G$ 是单群, 故 $\ker\rho = {1}$, 否则 $H=G$, 矛盾.
   因此存在 $G$ 到 $S_m$ 子群的同构.

   若 $m = 3$, 由于 $G$ 是单群, 故 $G \neq S_3$, $|G| \leqslant 3$.

   若 $m = 4$, 由于 $G$ 是单群, 故 $G \neq S_4, G \neq A_4$,
   若 $|G| = 8$, $p^n$ 阶群有非平凡的中心元素, 矛盾.
   若 $|G| = 6$, 与 $[G:H] = 4$ 矛盾, 故 $|G| \leqslant 3$.

4. 设 $H$ 是无限群 $G$ 的一个具有有限指数的真子群. 试证, $G$ 一定含有一个有限指数的真正规子群.

   证明:

   设 $[G:H] = m$, 令 $\Sigma = \{aH | a \in G\}$, 则有 $G$ 对 $\Sigma$ 的左诱导表示.
   考虑 $\ker\rho = \cap_{a \in G}{aHa^{-1}}$, $\ker\rho \lhd G$, $G/\ker\rho$ 同构于 $S_m$ 的某个子群,
   故 $[G:\ker\rho]|m!$, $G$ 对 $\ker\rho$ 的指数有限.

5. 求 $S_3$ 的自同构群.

   证明:

   考虑 $G = S_3$ 的二阶子群组成的集合 $\Sigma = \{A_1, A_2, A_3\}$, 则有 $Aut(G)$ 到 $\Sigma$ 的自然作用 $\rho$,
   $\ker\rho = 1$, 故存在 $Aut(G)$ 到 $S_3=S(\Sigma)$ 的同态, $Aut(G) \leqslant S_{3}$.

   另一方面, 考虑 $G$ 的内自同构群 $Inn(G)$, 则有 $S_3$ 到 $Inn(G)$ 的同态, 从而有
   $S_3/C(S_3)$ 到 $Inn(G)$ 的子群的同构, 从而 $S_3 \leqslant Inn(G)$.

   综上, $Aut(G) = S_3$.
