#+OPTIONS: author:nil ^:{}
#+HUGO_FRONT_MATTER_FORMAT: YAML
#+HUGO_BASE_DIR: ~/blog/
#+HUGO_SECTION: posts
#+DATE:<2023-12-10 Sun>
#+HUGO_CUSTOM_FRONT_MATTER: :toc true
#+HUGO_AUTO_SET_LASTMOD: t
#+HUGO_TAGS: "Abstract Algebra"
#+HUGO_DRAFT: false
#+TITLE: 子群和陪集分解
* 例题
1. $A$, $B$ 是群 $G$ 的两个子群. 试证:  $$AB \le G \text{ 当且仅当 } AB = BA.$$
   证明:

   $\Rightarrow$:
   $\forall a \in A, b \in B, ab \in AB$, $AB$ 是个群, 所以 $(ab)^{-1} = b^{-1}a^{-1} \in AB$,
   同时 $b^{-1}a^{-1} \in BA$,
   
   所以 $AB \subset BA$. 又因为 $\forall ba \in BA$, $(ba)^{-1} = a^{-1}b^{-1} \in AB$, 所以 $BA \subset AB$,

   故 $AB = BA$

   $\Leftarrow$:
   对于 $a, a^{'} \in A, b, b^{'} \in B, ab \in AB, a^{'}b^{'} \in AB$,
   
   $AB = BA$, 则 $\exists$ $a^{''} \in A, b^{''} \in B, a^{''}b^{''} = ba^{'}$,
   $aba^{'}b^{'} = aa^{''}b^{''}b^{'} \in AB$,

   所以 $AB$ 运算封闭, $1 \in AB$ 显然, 可逆易证, 故 $AB \le G$

2. 令 $G=GL(n, C)$, $P$ 是主对角线上的元素均为 $1$ 的 $n \times n$ 上三角矩阵.
   确定 $N_G(P)$, $C_G(P)$ 和 $P$ 的中心 $C(P)$.

   $N_G(P) = \{g|g^{-1}Pg = P\}$, 考虑一个初等矩阵 $g$ 的三种情况
   1) 倍乘. 显然 $g \in N_G(P)$.

   2) 交换. 对于一个交换型初等矩阵, 根据左行右列的原则, 显然不满足 $\forall p \in P, g^{-1}pg \in P$

   3) 倍加. 当非零元在主对角线下方时, 不满足 $\forall p \in P, g^{-1}pg \in P$.
      当非零元在主对角线上方时, $\forall p \in P, g^{-1}pg \in P$.
   故 $N_G(P)$ 由所有的可逆上三角矩阵组成.
   类似可得, $C_G(P) = E$, $C_P = E$.

3. 试证有限群 $G$ 的一个真子群的全部共轭子群不能覆盖整个群 $G$. 结论对无限群是否成立?

   证明:
   设 $H < G$, 则 $H$ 的共轭子群的个数为 $[G:N_G(H)]$, 每个共轭子群的阶为 $|H|$.

   根据拉格朗日定理, $G$ 为有限群, 故 $|G| = [G:N_G(H)]]|N_G(H)|$, 由于 $|N_G(H)| \ge |H|$,

   $|G| \ge [G:N_G(H)]|H|$, 考虑到 $H$ 的共轭子群至少有两个 (因为 $H$ 是真子群),
   且两个共轭子群的交至少含有 $1$, 故必定有 $|G| > \bigcup_{g \in G} g_{-1}Hg$, 证毕.

   结论对无限群不一定成立. 考虑 $GL_C$,
   全体上三角矩阵显然构成一个真子群。而由 Jordan 标准形理论，任意矩阵必相似于一个上三角矩阵.

4. 设 $G$ 是奇数阶有限群, $\alpha \in Aut(G)$ 且 $a^2 = 1$. 令
   \[
   G_1 = \{g \in G|\alpha(g) = g\}, G_{-1} = \{g \in G|\alpha(g) = g_{-1}\}.
   \]
   试证:$G = G_1G_{-1}$ 且 $G_1 \cap G_{-1} = 1$.

   证明:
   $\forall g \in G$, 令 $g^{-1}\alpha(g) = x^2$,

   $\alpha(x^2) = \alpha^{-1}(g)g = (g^{-1}\alpha(g))^{-1} = x^{-2}$,

   设 $\alpha(x), x$ 的阶分别为 $m, n$, 令 $2w = 1(mod[m, n])$, 上式两边同时取 $w$ 次幂, 可得 $\alpha(x) = x^{-1}$

   $\alpha(gx) = \alpha(g)x^{-1} = gx^2x^{-1} = gx$, $\alpha(x^{-1}) = x$,
   故 $g = gxx^{-1} \in G_1G_{-1}$.

   若有 $g \not= 1, g \in G_1, g \in G_{-1}$, 则 $g_{-1} = g, g^2 = 1$, 而 $G$ 是奇数阶群, 不存在偶数阶元素, 故矛盾, 故 $G_1 \cap G_{-1} = 1$

5. 设 $G$ 是有限阿贝尔群,试证:$g$ 对应到 $g^k$ 是 $G$ 的一个自同构当且仅当 $k$ 和 $|G|$ 互素.

   证明:
   显然这是一个自同态, 仅需证明双射, 又因 $G$ 是有限群, 故仅需证明单射. 记这个映射为 $f$, 则

   $\Rightarrow$
   f 是单射, 则 $\forall g, g\prime \in G, g \neq g\prime \Rightarrow g^k \neq (g\prime)^{k}$, 特别的, $\forall g \not= 1 \in G, g^k \not= 1$, 即 $k \not= 0(mod |g|)$,

   设 $(k, |g|) = p > 1$, 则 $k = pq, |g| = pr, (g^r)^p = 1$, (g$^r)^k = (g^r)^{pq} = 1$, 与单射矛盾, 故 $(k, |g|) = 1$, 因此 $k 和 |G|$ 互素.

   $\Leftarrow$
   $k 和 |G| 互素$, 则 $g^k = (g\prime)^k \Rightarrow g^{-1}g\prime = 1 \Rightarrow g = g\prime$, 故 $f$ 为单射.
